// src/types/index.ts

// Re-export types from common.ts
export type {
  Dialect,
  OnDeleteAction,
  ForeignKeyConfig,
  ColumnConfig,
  IndexConfig,
  CompositePrimaryKeyConfig,
  TableColumns,
  TableConfig,
  InferColumnType,
  InferModelType,
  SelectFields,
  IncludeRelationOptions,
  IncludeClause,
  InferSelectedModelType,
  TypedIncludeRelationOptions,
  EnhancedIncludeClauseEntry,
  EnhancedIncludeClause,
  InferIncludedRelationModel,
  ShapedResultItem,
  FunctionArg,
  BaseFunctionDescriptor,
  UnaryFunctionDescriptor,
  VariadicFunctionDescriptor,
  LowerFunctionDescriptor,
  UpperFunctionDescriptor,
  CountFunctionDescriptor,
  ConcatFunctionDescriptor,
  LikeFunctionDescriptor,
  RegexpContainsFunctionDescriptor,
  OrmFunctionDescriptor,
  SQL, // SQL interface is defined in common.ts
  ColumnSnapshot,
  IndexSnapshot,
  CompositePrimaryKeySnapshot,
  InterleaveSnapshot,
  TableSnapshot,
  SchemaSnapshot,
  ColumnDiffAction,
  IndexDiffAction,
  PrimaryKeyDiffAction,
  InterleaveDiffAction,
  TableDiffAction,
  SchemaDiff,
  MigrationExecutor,
  PreparedQuery,
} from "./common.js";

// Re-export types from adapter.ts
export type {
  QueryResultRow,
  DatabaseAdapter,
  Transaction,
  AffectedRows,
  ConnectionOptions,
} from "./adapter.js";
