name: CI

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup Bun
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # Cache dependencies
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      # Install dependencies
      - name: Install dependencies
        run: bun install

      # Run linting
      - name: Run lint
        run: bun run lint

      # Test build process
      - name: Build application
        run: bun run build

      # Run unit tests
      - name: Run unit tests
        run: bun run test
